// <auto-generated />
using System;
using MathAnalysisAI.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MathAnalysisAI.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260529155549_AddMathAnalysisSeedData")]
    partial class AddMathAnalysisSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MathAnalysisAI.Server.Models.AnalysisResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("AiJudgedCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("AnalysisMode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ChapterName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CourseName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Difficulty")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool?>("FinalCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("FinalCorrectSource")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("KnowledgePointsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MistakeTagsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProblemId")
                        .HasColumnType("int");

                    b.Property<string>("ProblemType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RawResponseJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewSuggestionsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StandardSolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentSolutionId")
                        .HasColumnType("int");

                    b.Property<string>("StudentSolutionReview")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("StudentSolutionId");

                    b.HasIndex("ProblemId", "CreatedAt");

                    b.ToTable("AnalysisResults");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.AnalysisVisualization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnalysisResultId")
                        .HasColumnType("int");

                    b.Property<string>("Caption")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("CommandsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("StepBindingJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValidationMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("ValidationStatus")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ViewConfigJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisualizationType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisResultId");

                    b.ToTable("AnalysisVisualizations");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RealName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("SchoolName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("StudentNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("StudentNumber");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "OrderIndex", "Name");

                    b.ToTable("Chapters");

                    b.HasData(
                        new
                        {
                            Id = 301,
                            Code = "ma.limit",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "函数与数列极限基础",
                            Name = "极限",
                            OrderIndex = 1
                        },
                        new
                        {
                            Id = 302,
                            Code = "ma.continuity",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "函数连续与间断",
                            Name = "连续",
                            OrderIndex = 2
                        },
                        new
                        {
                            Id = 303,
                            Code = "ma.derivative",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "导数定义与求导",
                            Name = "导数与微分",
                            OrderIndex = 3
                        },
                        new
                        {
                            Id = 304,
                            Code = "ma.mean_value_theorem",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rolle 与拉格朗日中值定理",
                            Name = "微分中值定理",
                            OrderIndex = 4
                        },
                        new
                        {
                            Id = 305,
                            Code = "ma.indefinite_integral",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "原函数与积分技巧",
                            Name = "不定积分",
                            OrderIndex = 5
                        },
                        new
                        {
                            Id = 306,
                            Code = "ma.definite_integral",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "黎曼积分与计算",
                            Name = "定积分",
                            OrderIndex = 6
                        },
                        new
                        {
                            Id = 307,
                            Code = "ma.improper_integral",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "无界区间与无界函数积分",
                            Name = "反常积分",
                            OrderIndex = 7
                        },
                        new
                        {
                            Id = 308,
                            Code = "ma.numeric_series",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "级数收敛性判别",
                            Name = "数项级数",
                            OrderIndex = 8
                        },
                        new
                        {
                            Id = 309,
                            Code = "ma.function_series",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "一致收敛与函数项级数",
                            Name = "函数列与函数项级数",
                            OrderIndex = 9
                        },
                        new
                        {
                            Id = 310,
                            Code = "ma.power_series",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "收敛半径与展开",
                            Name = "幂级数",
                            OrderIndex = 10
                        },
                        new
                        {
                            Id = 311,
                            Code = "ma.multivariable_differential",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "偏导与全微分",
                            Name = "多元函数微分学",
                            OrderIndex = 11
                        });
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId", "Name")
                        .IsUnique();

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 200,
                            Code = "math_analysis",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "本科数学分析课程",
                            Name = "数学分析",
                            SubjectId = 100
                        });
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.KnowledgeDependency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DependencyType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("FromKnowledgePointId")
                        .HasColumnType("int");

                    b.Property<int>("ToKnowledgePointId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ToKnowledgePointId");

                    b.HasIndex("FromKnowledgePointId", "ToKnowledgePointId")
                        .IsUnique();

                    b.ToTable("KnowledgeDependencies");

                    b.HasData(
                        new
                        {
                            Id = 2001,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DependencyType = "prerequisite",
                            FromKnowledgePointId = 1001,
                            ToKnowledgePointId = 1005
                        },
                        new
                        {
                            Id = 2002,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DependencyType = "prerequisite",
                            FromKnowledgePointId = 1002,
                            ToKnowledgePointId = 1005
                        },
                        new
                        {
                            Id = 2003,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DependencyType = "prerequisite",
                            FromKnowledgePointId = 1005,
                            ToKnowledgePointId = 1009
                        },
                        new
                        {
                            Id = 2004,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DependencyType = "prerequisite",
                            FromKnowledgePointId = 1009,
                            ToKnowledgePointId = 1014
                        },
                        new
                        {
                            Id = 2005,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DependencyType = "uses",
                            FromKnowledgePointId = 1014,
                            ToKnowledgePointId = 1018
                        },
                        new
                        {
                            Id = 2006,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DependencyType = "prerequisite",
                            FromKnowledgePointId = 1017,
                            ToKnowledgePointId = 1023
                        },
                        new
                        {
                            Id = 2007,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DependencyType = "uses",
                            FromKnowledgePointId = 1023,
                            ToKnowledgePointId = 1024
                        },
                        new
                        {
                            Id = 2008,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DependencyType = "prerequisite",
                            FromKnowledgePointId = 1029,
                            ToKnowledgePointId = 1037
                        },
                        new
                        {
                            Id = 2009,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DependencyType = "uses",
                            FromKnowledgePointId = 1034,
                            ToKnowledgePointId = 1039
                        },
                        new
                        {
                            Id = 2010,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DependencyType = "often_confused",
                            FromKnowledgePointId = 1030,
                            ToKnowledgePointId = 1027
                        },
                        new
                        {
                            Id = 2011,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DependencyType = "prerequisite",
                            FromKnowledgePointId = 1012,
                            ToKnowledgePointId = 1042
                        },
                        new
                        {
                            Id = 2012,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DependencyType = "uses",
                            FromKnowledgePointId = 1041,
                            ToKnowledgePointId = 1043
                        });
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.KnowledgePoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChapterId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("CourseId", "ChapterId", "Name");

                    b.ToTable("KnowledgePoints");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            ChapterId = 301,
                            Code = "ma.limit.sequence_limit",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "数列收敛定义与判定",
                            Name = "数列极限定义"
                        },
                        new
                        {
                            Id = 1002,
                            ChapterId = 301,
                            Code = "ma.limit.epsilon_delta",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "函数极限定义与几何直观",
                            Name = "函数极限定义"
                        },
                        new
                        {
                            Id = 1003,
                            ChapterId = 301,
                            Code = "ma.limit.infinitesimal_infinite",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "无穷小等价与比较",
                            Name = "无穷小与无穷大"
                        },
                        new
                        {
                            Id = 1004,
                            ChapterId = 301,
                            Code = "ma.limit.algebra_rules",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "极限运算法则",
                            Name = "极限四则运算"
                        },
                        new
                        {
                            Id = 1005,
                            ChapterId = 302,
                            Code = "ma.continuity.definition",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "点连续与区间连续",
                            Name = "连续定义"
                        },
                        new
                        {
                            Id = 1006,
                            ChapterId = 302,
                            Code = "ma.continuity.discontinuity_types",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "可去/跳跃/无穷间断",
                            Name = "间断点分类"
                        },
                        new
                        {
                            Id = 1007,
                            ChapterId = 302,
                            Code = "ma.continuity.properties",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "介值与最值性质",
                            Name = "连续函数性质"
                        },
                        new
                        {
                            Id = 1008,
                            ChapterId = 302,
                            Code = "ma.continuity.uniform_continuity",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "一致连续定义",
                            Name = "一致连续初步"
                        },
                        new
                        {
                            Id = 1009,
                            ChapterId = 303,
                            Code = "ma.derivative.definition",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "差商极限与导数",
                            Name = "导数定义"
                        },
                        new
                        {
                            Id = 1010,
                            ChapterId = 303,
                            Code = "ma.derivative.continuity_relation",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "可导蕴含连续",
                            Name = "可导与连续关系"
                        },
                        new
                        {
                            Id = 1011,
                            ChapterId = 303,
                            Code = "ma.derivative.rules",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "四则与复合函数求导",
                            Name = "求导法则"
                        },
                        new
                        {
                            Id = 1012,
                            ChapterId = 303,
                            Code = "ma.derivative.differential_linearization",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "微分定义与几何意义",
                            Name = "微分与线性近似"
                        },
                        new
                        {
                            Id = 1013,
                            ChapterId = 304,
                            Code = "ma.mean_value_theorem.rolle",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rolle 定理条件与结论",
                            Name = "Rolle 定理"
                        },
                        new
                        {
                            Id = 1014,
                            ChapterId = 304,
                            Code = "ma.mean_value_theorem.lagrange",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "平均变化率与瞬时变化率",
                            Name = "拉格朗日中值定理"
                        },
                        new
                        {
                            Id = 1015,
                            ChapterId = 304,
                            Code = "ma.mean_value_theorem.cauchy",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "中值定理推广",
                            Name = "柯西中值定理"
                        },
                        new
                        {
                            Id = 1016,
                            ChapterId = 304,
                            Code = "ma.mean_value_theorem.lhopital",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "未定式极限计算",
                            Name = "洛必达法则"
                        },
                        new
                        {
                            Id = 1017,
                            ChapterId = 305,
                            Code = "ma.indefinite_integral.antiderivative",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "原函数与不定积分定义",
                            Name = "原函数概念"
                        },
                        new
                        {
                            Id = 1018,
                            ChapterId = 305,
                            Code = "ma.indefinite_integral.substitution",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "第一类与第二类换元",
                            Name = "换元积分法"
                        },
                        new
                        {
                            Id = 1019,
                            ChapterId = 305,
                            Code = "ma.indefinite_integral.integration_by_parts",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "分部积分公式应用",
                            Name = "分部积分法"
                        },
                        new
                        {
                            Id = 1020,
                            ChapterId = 305,
                            Code = "ma.indefinite_integral.rational_function",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "部分分式分解",
                            Name = "有理函数积分"
                        },
                        new
                        {
                            Id = 1021,
                            ChapterId = 306,
                            Code = "ma.definite_integral.definition",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "黎曼和与定积分",
                            Name = "定积分定义"
                        },
                        new
                        {
                            Id = 1022,
                            ChapterId = 306,
                            Code = "ma.definite_integral.mean_value_theorem",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "积分中值定理",
                            Name = "积分中值定理"
                        },
                        new
                        {
                            Id = 1023,
                            ChapterId = 306,
                            Code = "ma.definite_integral.newton_leibniz",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "微积分基本定理",
                            Name = "牛顿-莱布尼茨公式"
                        },
                        new
                        {
                            Id = 1024,
                            ChapterId = 306,
                            Code = "ma.definite_integral.applications",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "面积与体积计算",
                            Name = "定积分应用"
                        },
                        new
                        {
                            Id = 1025,
                            ChapterId = 307,
                            Code = "ma.improper_integral.infinite_interval",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "积分上限趋于无穷",
                            Name = "无穷区间反常积分"
                        },
                        new
                        {
                            Id = 1026,
                            ChapterId = 307,
                            Code = "ma.improper_integral.unbounded_function",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "积分区间端点无界",
                            Name = "无界函数反常积分"
                        },
                        new
                        {
                            Id = 1027,
                            ChapterId = 307,
                            Code = "ma.improper_integral.comparison_test",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "反常积分比较判别",
                            Name = "比较判别法"
                        },
                        new
                        {
                            Id = 1028,
                            ChapterId = 307,
                            Code = "ma.improper_integral.convergence_criteria",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "常见反常积分判定",
                            Name = "收敛与发散判定"
                        },
                        new
                        {
                            Id = 1029,
                            ChapterId = 308,
                            Code = "ma.numeric_series.convergence_definition",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "部分和与收敛",
                            Name = "级数收敛定义"
                        },
                        new
                        {
                            Id = 1030,
                            ChapterId = 308,
                            Code = "ma.numeric_series.positive_series_tests",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "比较、比值、根值判别",
                            Name = "正项级数判别"
                        },
                        new
                        {
                            Id = 1031,
                            ChapterId = 308,
                            Code = "ma.numeric_series.alternating_series_test",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Leibniz 判别法",
                            Name = "交错级数判别"
                        },
                        new
                        {
                            Id = 1032,
                            ChapterId = 308,
                            Code = "ma.numeric_series.absolute_conditional",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "绝对收敛关系",
                            Name = "绝对与条件收敛"
                        },
                        new
                        {
                            Id = 1033,
                            ChapterId = 309,
                            Code = "ma.function_series.pointwise_convergence",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "逐点收敛定义",
                            Name = "函数列逐点收敛"
                        },
                        new
                        {
                            Id = 1034,
                            ChapterId = 309,
                            Code = "ma.function_series.uniform_convergence",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "一致收敛与范数",
                            Name = "一致收敛定义"
                        },
                        new
                        {
                            Id = 1035,
                            ChapterId = 309,
                            Code = "ma.function_series.weierstrass_m_test",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "一致收敛判别",
                            Name = "Weierstrass 判别法"
                        },
                        new
                        {
                            Id = 1036,
                            ChapterId = 309,
                            Code = "ma.function_series.limit_exchange",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "极限与积分/导数交换",
                            Name = "一致收敛交换极限"
                        },
                        new
                        {
                            Id = 1037,
                            ChapterId = 310,
                            Code = "ma.power_series.radius_of_convergence",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "幂级数基本形式",
                            Name = "幂级数与收敛半径"
                        },
                        new
                        {
                            Id = 1038,
                            ChapterId = 310,
                            Code = "ma.power_series.interval_of_convergence",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "端点收敛性讨论",
                            Name = "收敛区间判定"
                        },
                        new
                        {
                            Id = 1039,
                            ChapterId = 310,
                            Code = "ma.power_series.termwise_operations",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "逐项求导与积分",
                            Name = "幂级数逐项运算"
                        },
                        new
                        {
                            Id = 1040,
                            ChapterId = 310,
                            Code = "ma.power_series.taylor_expansion",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "常见函数的幂级数展开",
                            Name = "Taylor 展开"
                        },
                        new
                        {
                            Id = 1041,
                            ChapterId = 311,
                            Code = "ma.multivariable_differential.partial_derivative",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "多元函数偏导",
                            Name = "偏导数定义"
                        },
                        new
                        {
                            Id = 1042,
                            ChapterId = 311,
                            Code = "ma.multivariable_differential.total_differential",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "全微分存在条件",
                            Name = "全微分"
                        },
                        new
                        {
                            Id = 1043,
                            ChapterId = 311,
                            Code = "ma.multivariable_differential.directional_gradient",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "梯度及几何意义",
                            Name = "方向导数与梯度"
                        },
                        new
                        {
                            Id = 1044,
                            ChapterId = 311,
                            Code = "ma.multivariable_differential.extrema_lagrange",
                            CourseId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hessian 与拉格朗日乘子",
                            Name = "极值与条件极值"
                        });
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.LLMRequestLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnalysisResultId")
                        .HasColumnType("int");

                    b.Property<int?>("CompletionTokenCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("int");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("PromptTokenCount")
                        .HasColumnType("int");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("TotalTokenCount")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisResultId");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "ModelName", "CreatedAt");

                    b.ToTable("LLMRequestLogs");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.MistakeRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnalysisResultId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int?>("KnowledgePointId")
                        .HasColumnType("int");

                    b.Property<string>("MistakeTag")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisResultId");

                    b.HasIndex("KnowledgePointId");

                    b.ToTable("MistakeRecords");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.Problem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChapterId")
                        .HasColumnType("int");

                    b.Property<string>("ContentLatex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Difficulty")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ProblemType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SourceFilePath")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Title")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("CourseId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Problems");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.PromptProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("OutputSchemaJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPromptTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "Mode", "Version");

                    b.ToTable("PromptProfiles");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.StudentSolution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProblemId")
                        .HasColumnType("int");

                    b.Property<string>("SolutionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProblemId");

                    b.HasIndex("UserId");

                    b.ToTable("StudentSolutions");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "本科数学学科",
                            Name = "数学"
                        });
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.UserCourseStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AccuracyRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RankingScore")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WrongCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId", "CourseId")
                        .IsUnique();

                    b.ToTable("UserCourseStats");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.UserKnowledgeState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CorrectCount")
                        .HasColumnType("int");

                    b.Property<int>("KnowledgePointId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MasteryLevel")
                        .HasColumnType("int");

                    b.Property<int>("PracticeCount")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgePointId");

                    b.HasIndex("UserId", "KnowledgePointId")
                        .IsUnique();

                    b.ToTable("UserKnowledgeStates");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.WrongQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CleanLatex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorAnalysis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImprovementSuggestion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KnowledgePoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverallEvaluation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawLatex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StandardSolution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WrongQuestions");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.AnalysisResult", b =>
                {
                    b.HasOne("MathAnalysisAI.Server.Models.Problem", "Problem")
                        .WithMany("AnalysisResults")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MathAnalysisAI.Server.Models.StudentSolution", "StudentSolution")
                        .WithMany("AnalysisResults")
                        .HasForeignKey("StudentSolutionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Problem");

                    b.Navigation("StudentSolution");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.AnalysisVisualization", b =>
                {
                    b.HasOne("MathAnalysisAI.Server.Models.AnalysisResult", "AnalysisResult")
                        .WithMany("Visualizations")
                        .HasForeignKey("AnalysisResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisResult");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.Chapter", b =>
                {
                    b.HasOne("MathAnalysisAI.Server.Models.Course", "Course")
                        .WithMany("Chapters")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.Course", b =>
                {
                    b.HasOne("MathAnalysisAI.Server.Models.Subject", "Subject")
                        .WithMany("Courses")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.KnowledgeDependency", b =>
                {
                    b.HasOne("MathAnalysisAI.Server.Models.KnowledgePoint", "FromKnowledgePoint")
                        .WithMany("OutgoingDependencies")
                        .HasForeignKey("FromKnowledgePointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MathAnalysisAI.Server.Models.KnowledgePoint", "ToKnowledgePoint")
                        .WithMany("IncomingDependencies")
                        .HasForeignKey("ToKnowledgePointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromKnowledgePoint");

                    b.Navigation("ToKnowledgePoint");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.KnowledgePoint", b =>
                {
                    b.HasOne("MathAnalysisAI.Server.Models.Chapter", "Chapter")
                        .WithMany("KnowledgePoints")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MathAnalysisAI.Server.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.LLMRequestLog", b =>
                {
                    b.HasOne("MathAnalysisAI.Server.Models.AnalysisResult", "AnalysisResult")
                        .WithMany()
                        .HasForeignKey("AnalysisResultId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MathAnalysisAI.Server.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AnalysisResult");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.MistakeRecord", b =>
                {
                    b.HasOne("MathAnalysisAI.Server.Models.AnalysisResult", "AnalysisResult")
                        .WithMany("MistakeRecords")
                        .HasForeignKey("AnalysisResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MathAnalysisAI.Server.Models.KnowledgePoint", "KnowledgePoint")
                        .WithMany("MistakeRecords")
                        .HasForeignKey("KnowledgePointId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AnalysisResult");

                    b.Navigation("KnowledgePoint");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.Problem", b =>
                {
                    b.HasOne("MathAnalysisAI.Server.Models.Chapter", "Chapter")
                        .WithMany("Problems")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MathAnalysisAI.Server.Models.Course", "Course")
                        .WithMany("Problems")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MathAnalysisAI.Server.Models.AppUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Chapter");

                    b.Navigation("Course");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.PromptProfile", b =>
                {
                    b.HasOne("MathAnalysisAI.Server.Models.Course", "Course")
                        .WithMany("PromptProfiles")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.StudentSolution", b =>
                {
                    b.HasOne("MathAnalysisAI.Server.Models.Problem", "Problem")
                        .WithMany("StudentSolutions")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MathAnalysisAI.Server.Models.AppUser", "User")
                        .WithMany("StudentSolutions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Problem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.UserCourseStats", b =>
                {
                    b.HasOne("MathAnalysisAI.Server.Models.Course", "Course")
                        .WithMany("UserCourseStats")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MathAnalysisAI.Server.Models.AppUser", "User")
                        .WithMany("UserCourseStats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.UserKnowledgeState", b =>
                {
                    b.HasOne("MathAnalysisAI.Server.Models.KnowledgePoint", "KnowledgePoint")
                        .WithMany("UserKnowledgeStates")
                        .HasForeignKey("KnowledgePointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MathAnalysisAI.Server.Models.AppUser", "User")
                        .WithMany("UserKnowledgeStates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KnowledgePoint");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.AnalysisResult", b =>
                {
                    b.Navigation("MistakeRecords");

                    b.Navigation("Visualizations");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.AppUser", b =>
                {
                    b.Navigation("StudentSolutions");

                    b.Navigation("UserCourseStats");

                    b.Navigation("UserKnowledgeStates");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.Chapter", b =>
                {
                    b.Navigation("KnowledgePoints");

                    b.Navigation("Problems");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.Course", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("Problems");

                    b.Navigation("PromptProfiles");

                    b.Navigation("UserCourseStats");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.KnowledgePoint", b =>
                {
                    b.Navigation("IncomingDependencies");

                    b.Navigation("MistakeRecords");

                    b.Navigation("OutgoingDependencies");

                    b.Navigation("UserKnowledgeStates");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.Problem", b =>
                {
                    b.Navigation("AnalysisResults");

                    b.Navigation("StudentSolutions");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.StudentSolution", b =>
                {
                    b.Navigation("AnalysisResults");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.Subject", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
