// <auto-generated />
using System;
using MathAnalysisAI.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MathAnalysisAI.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260529152908_AddLearningPlatformSchema")]
    partial class AddLearningPlatformSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MathAnalysisAI.Server.Models.AnalysisResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("AiJudgedCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("AnalysisMode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ChapterName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CourseName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Difficulty")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool?>("FinalCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("FinalCorrectSource")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("KnowledgePointsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MistakeTagsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProblemId")
                        .HasColumnType("int");

                    b.Property<string>("ProblemType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RawResponseJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewSuggestionsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StandardSolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentSolutionId")
                        .HasColumnType("int");

                    b.Property<string>("StudentSolutionReview")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("StudentSolutionId");

                    b.HasIndex("ProblemId", "CreatedAt");

                    b.ToTable("AnalysisResults");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.AnalysisVisualization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnalysisResultId")
                        .HasColumnType("int");

                    b.Property<string>("Caption")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("CommandsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("StepBindingJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValidationMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("ValidationStatus")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ViewConfigJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisualizationType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisResultId");

                    b.ToTable("AnalysisVisualizations");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RealName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("SchoolName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("StudentNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("StudentNumber");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "OrderIndex", "Name");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId", "Name")
                        .IsUnique();

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.KnowledgeDependency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DependencyType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("FromKnowledgePointId")
                        .HasColumnType("int");

                    b.Property<int>("ToKnowledgePointId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ToKnowledgePointId");

                    b.HasIndex("FromKnowledgePointId", "ToKnowledgePointId")
                        .IsUnique();

                    b.ToTable("KnowledgeDependencies");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.KnowledgePoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChapterId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("CourseId", "ChapterId", "Name");

                    b.ToTable("KnowledgePoints");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.LLMRequestLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnalysisResultId")
                        .HasColumnType("int");

                    b.Property<int?>("CompletionTokenCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("int");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("PromptTokenCount")
                        .HasColumnType("int");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("TotalTokenCount")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisResultId");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "ModelName", "CreatedAt");

                    b.ToTable("LLMRequestLogs");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.MistakeRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnalysisResultId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int?>("KnowledgePointId")
                        .HasColumnType("int");

                    b.Property<string>("MistakeTag")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisResultId");

                    b.HasIndex("KnowledgePointId");

                    b.ToTable("MistakeRecords");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.Problem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChapterId")
                        .HasColumnType("int");

                    b.Property<string>("ContentLatex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Difficulty")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ProblemType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SourceFilePath")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Title")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("CourseId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Problems");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.PromptProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("OutputSchemaJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPromptTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "Mode", "Version");

                    b.ToTable("PromptProfiles");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.StudentSolution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProblemId")
                        .HasColumnType("int");

                    b.Property<string>("SolutionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProblemId");

                    b.HasIndex("UserId");

                    b.ToTable("StudentSolutions");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.UserCourseStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AccuracyRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RankingScore")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WrongCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId", "CourseId")
                        .IsUnique();

                    b.ToTable("UserCourseStats");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.UserKnowledgeState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CorrectCount")
                        .HasColumnType("int");

                    b.Property<int>("KnowledgePointId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MasteryLevel")
                        .HasColumnType("int");

                    b.Property<int>("PracticeCount")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgePointId");

                    b.HasIndex("UserId", "KnowledgePointId")
                        .IsUnique();

                    b.ToTable("UserKnowledgeStates");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.WrongQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CleanLatex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorAnalysis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImprovementSuggestion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KnowledgePoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverallEvaluation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawLatex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StandardSolution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WrongQuestions");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.AnalysisResult", b =>
                {
                    b.HasOne("MathAnalysisAI.Server.Models.Problem", "Problem")
                        .WithMany("AnalysisResults")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MathAnalysisAI.Server.Models.StudentSolution", "StudentSolution")
                        .WithMany("AnalysisResults")
                        .HasForeignKey("StudentSolutionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Problem");

                    b.Navigation("StudentSolution");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.AnalysisVisualization", b =>
                {
                    b.HasOne("MathAnalysisAI.Server.Models.AnalysisResult", "AnalysisResult")
                        .WithMany("Visualizations")
                        .HasForeignKey("AnalysisResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisResult");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.Chapter", b =>
                {
                    b.HasOne("MathAnalysisAI.Server.Models.Course", "Course")
                        .WithMany("Chapters")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.Course", b =>
                {
                    b.HasOne("MathAnalysisAI.Server.Models.Subject", "Subject")
                        .WithMany("Courses")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.KnowledgeDependency", b =>
                {
                    b.HasOne("MathAnalysisAI.Server.Models.KnowledgePoint", "FromKnowledgePoint")
                        .WithMany("OutgoingDependencies")
                        .HasForeignKey("FromKnowledgePointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MathAnalysisAI.Server.Models.KnowledgePoint", "ToKnowledgePoint")
                        .WithMany("IncomingDependencies")
                        .HasForeignKey("ToKnowledgePointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromKnowledgePoint");

                    b.Navigation("ToKnowledgePoint");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.KnowledgePoint", b =>
                {
                    b.HasOne("MathAnalysisAI.Server.Models.Chapter", "Chapter")
                        .WithMany("KnowledgePoints")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MathAnalysisAI.Server.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.LLMRequestLog", b =>
                {
                    b.HasOne("MathAnalysisAI.Server.Models.AnalysisResult", "AnalysisResult")
                        .WithMany()
                        .HasForeignKey("AnalysisResultId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MathAnalysisAI.Server.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AnalysisResult");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.MistakeRecord", b =>
                {
                    b.HasOne("MathAnalysisAI.Server.Models.AnalysisResult", "AnalysisResult")
                        .WithMany("MistakeRecords")
                        .HasForeignKey("AnalysisResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MathAnalysisAI.Server.Models.KnowledgePoint", "KnowledgePoint")
                        .WithMany("MistakeRecords")
                        .HasForeignKey("KnowledgePointId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AnalysisResult");

                    b.Navigation("KnowledgePoint");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.Problem", b =>
                {
                    b.HasOne("MathAnalysisAI.Server.Models.Chapter", "Chapter")
                        .WithMany("Problems")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MathAnalysisAI.Server.Models.Course", "Course")
                        .WithMany("Problems")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MathAnalysisAI.Server.Models.AppUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Chapter");

                    b.Navigation("Course");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.PromptProfile", b =>
                {
                    b.HasOne("MathAnalysisAI.Server.Models.Course", "Course")
                        .WithMany("PromptProfiles")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.StudentSolution", b =>
                {
                    b.HasOne("MathAnalysisAI.Server.Models.Problem", "Problem")
                        .WithMany("StudentSolutions")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MathAnalysisAI.Server.Models.AppUser", "User")
                        .WithMany("StudentSolutions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Problem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.UserCourseStats", b =>
                {
                    b.HasOne("MathAnalysisAI.Server.Models.Course", "Course")
                        .WithMany("UserCourseStats")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MathAnalysisAI.Server.Models.AppUser", "User")
                        .WithMany("UserCourseStats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.UserKnowledgeState", b =>
                {
                    b.HasOne("MathAnalysisAI.Server.Models.KnowledgePoint", "KnowledgePoint")
                        .WithMany("UserKnowledgeStates")
                        .HasForeignKey("KnowledgePointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MathAnalysisAI.Server.Models.AppUser", "User")
                        .WithMany("UserKnowledgeStates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KnowledgePoint");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.AnalysisResult", b =>
                {
                    b.Navigation("MistakeRecords");

                    b.Navigation("Visualizations");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.AppUser", b =>
                {
                    b.Navigation("StudentSolutions");

                    b.Navigation("UserCourseStats");

                    b.Navigation("UserKnowledgeStates");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.Chapter", b =>
                {
                    b.Navigation("KnowledgePoints");

                    b.Navigation("Problems");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.Course", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("Problems");

                    b.Navigation("PromptProfiles");

                    b.Navigation("UserCourseStats");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.KnowledgePoint", b =>
                {
                    b.Navigation("IncomingDependencies");

                    b.Navigation("MistakeRecords");

                    b.Navigation("OutgoingDependencies");

                    b.Navigation("UserKnowledgeStates");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.Problem", b =>
                {
                    b.Navigation("AnalysisResults");

                    b.Navigation("StudentSolutions");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.StudentSolution", b =>
                {
                    b.Navigation("AnalysisResults");
                });

            modelBuilder.Entity("MathAnalysisAI.Server.Models.Subject", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
